# Generated by Django 4.0 on 2021-12-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerData',
            fields=[
                ('server_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
