# Generated by Django 4.0 on 2021-12-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdata',
            name='prefix',
            field=models.CharField(default='~', max_length=1),
        ),
    ]
