# Generated by Django 4.0 on 2021-12-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_base', '0003_botpermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotPermission',
        ),
    ]
