# Generated by Django 4.0 on 2021-12-08 01:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bot_base', '0004_delete_botpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverdata',
            name='prefix',
        ),
    ]
