# Generated by Django 4.0 on 2021-12-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_base', '0005_remove_serverdata_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdata',
            name='server_id',
            field=models.BigIntegerField(max_length=18, primary_key=True, serialize=False),
        ),
    ]
