# Generated by Django 4.0 on 2021-12-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_base', '0006_alter_serverdata_server_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdata',
            name='server_id',
            field=models.IntegerField(max_length=18, primary_key=True, serialize=False),
        ),
    ]
