# Generated by Django 4.0 on 2021-12-09 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('bot_base', '0008_alter_serverdata_server_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathCogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('parent_server',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_base.serverdata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('value', models.BigIntegerField(blank=True, null=True)),
                ('parent_cog',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.mathcogdata')),
            ],
            options={
                'unique_together': {('index', 'parent_cog')},
            },
        ),
    ]
