# Generated by Django 4.0 on 2021-12-09 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mathematics', '0002_alter_memoryentry_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryentry',
            name='parent_cog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mem',
                                    to='mathematics.mathcogdata'),
        ),
    ]
