# Generated by Django 4.0 on 2021-12-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0002_alter_memoryentry_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryentry',
            name='parent_cog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mem', to='mathematics.mathcogdata'),
        ),
    ]
