# Generated by Django 4.0 on 2021-12-08 17:21

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('bot_base', '0008_alter_serverdata_server_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationCogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('moderator_role_id', models.IntegerField(blank=True, null=True)),
                ('administrator_role_id', models.IntegerField(blank=True, null=True)),
                ('max_warnings_until_soft_ban', models.IntegerField(default=3)),
                ('max_warnings_until_permanent_ban', models.IntegerField(default=5)),
                ('parent_server',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_base.serverdata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('forgive_time', models.DurationField(default=datetime.timedelta(days=7))),
                ('date_created', models.DateField(auto_now_add=True)),
                ('parent_cog',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.moderationcogdata')),
            ],
        ),
        migrations.CreateModel(
            name='PermanentBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('parent_cog',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.moderationcogdata')),
            ],
        ),
        migrations.CreateModel(
            name='ModWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('forget_time', models.DurationField(default=datetime.timedelta(days=30))),
                ('date_created', models.DateField(auto_now_add=True)),
                ('parent_cog',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.moderationcogdata')),
            ],
        ),
    ]
