# Generated by Django 4.0 on 2021-12-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modwarning',
            name='reporter_id',
            field=models.IntegerField(default=111111111111111111),
            preserve_default=False,
        ),
    ]
