# Generated by Django 4.0 on 2021-12-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_modwarning_reporter_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermanentBan',
            new_name='Ban',
        ),
        migrations.RenameField(
            model_name='moderationcogdata',
            old_name='max_warnings_until_soft_ban',
            new_name='max_warnings_until_ban',
        ),
        migrations.RemoveField(
            model_name='moderationcogdata',
            name='max_warnings_until_permanent_ban',
        ),
        migrations.DeleteModel(
            name='SoftBan',
        ),
    ]
