# Generated by Django 4.0 on 2021-12-08 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('moderation', '0004_ban_banner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modwarning',
            name='parent_cog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings',
                                    to='moderation.moderationcogdata'),
        ),
        migrations.DeleteModel(
            name='Ban',
        ),
    ]
